### ISSUE TITLE
Encrypted Backup Extraction Issue

### ISSUE THREAD

**Issue by stark4n6** [prosch88/UFADE#2]
I'm trying Logical+ Backup and when it prompts for the backup passcode I'm supplying it but it says it's incorrect. I just reset it by erasing my settings so I know it's correct. Not sure if there is anything I should try next.

The device is an iPhone 13 with iOS 17.6.1.

**Comment by prosch88** [comment]
Are you using the compiled version or the "git cloned" one? This issue could be related to pymobiledevice3 as 17.6.1 is quite new. I'll update one of my devices to see if I can reproduce this.

**Comment by stark4n6** [comment]
compiled version (latest release for Windows)

**Comment by prosch88** [comment]
You could try the git version with newest packages to check if this occurres too.

**Comment by stark4n6** [comment]
I will test the git version as well as another test phone, will keep you updated on what I find out

**Comment by stark4n6** [comment]
iPhone 8 with iOS 16.3.1 worked fine with known backup password in both compiled and git version. I'm wondering if something changed with the latest iOS 17.6.1 release or thereabouts. Do you know if it previously worked with iOS 17?

**Comment by prosch88** [comment]
I had no problems with iOS 17.
Checked an iPhone SE 2 with 17.6.1 right now with the newest version without issues.
I will check the compiled version too.

**Comment by prosch88** [comment]
Are you using the same password on both devices?

**Comment by stark4n6** [comment]
Yes I was just using 1234, odd

**Comment by prosch88** [comment]
Same issue on the git version?

**Comment by prosch88** [comment]
As you installed the git version with it's dependencies.
Try:

python pymobiledevice3 backup2 encryption off 1234

and See if this raise an error.

**Comment by stark4n6** [comment]
I had a feeling this might be the issue, I think there is a conflict with the MDM on the phone 
![image](https://github.com/user-attachments/assets/a0dc80a2-8c8e-42af-8429-9914bb1c3538)

**Comment by prosch88** [comment]
Ah I see.
I'm planning to add some MDM stuff later (mostly importing mdm profiles as pmd3 allows this)

The mdm setting is enforcing encryption. The flow is not able to handle this right now. (it wants to set a New password). I'll may be able to adjust this if the error code differs when a wrong password is given.

**Comment by stark4n6** [comment]
Even when I type the correct password in the GUI it says it's wrong, so wondering if the MDM is causing that issue or something else, sorry for the headaches. I also ran into some other errors with closing the GUI and AFC extraction too if you want me to open up more issues.

**Comment by prosch88** [comment]
The AFC extraction is in the works currently as part of the generation of WatchOS UFDR Reports.

As for the GUI errors new issues are preferable.
Some problems only occur when using UFADE on Windows and I'm mostly coding on Linux.

**Comment by prosch88** [comment]
When the error message differs with the pymobiledevice3 command it would be possible to handle this case for the GUI.

**Comment by ogi82** [comment]
Hello, I have an iPhone SE 3rd with iOS 17.6.1. In the case of logical + backup extraction, backup decoding ends at 71% and throws an error. Please let me know if it can be repaired. Is ios 17.6.1 too new. Thank you for your reply

**Comment by prosch88** [comment]
Are you using the latest version cloned from Github? Or the compiled version?

**Comment by prosch88** [comment]
What's the error message?

**Comment by prosch88** [comment]
Just added some error handling. Try again wit the latest Github release.

**Comment by ogi82** [comment]
Backup is done completely, but decryption is at 71%. I am using the latest version of github. I am pasting the codes that the system throws
File "/home/luki/.local/lib/python3.10/site-packages/iOSbackup/__init__.py", line 985, in getFileDecryptedCopy
    mappedInFile = mmap.mmap(inFile.fileno(), length=0, prot=mmap.PROT_READ)
ValueError: cannot mmap an empty file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luki/UFADE/ufade.py", line 1255, in <module>
    wrapper(select_menu)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/luki/UFADE/ufade.py", line 99, in select_menu
    bu_menu()
  File "/home/luki/UFADE/ufade.py", line 125, in bu_menu
    perf_logical_plus(None)
  File "/home/luki/UFADE/ufade.py", line 482, in perf_logical_plus
    iTunes_bu("Logical+")                                                                                                   #call iTunes Backup with "Logical+" written in dialog
  File "/home/luki/UFADE/ufade.py", line 464, in iTunes_bu
    select_menu(main_screen)
  File "/home/luki/UFADE/ufade.py", line 99, in select_menu
    bu_menu()                                                                       71%       
  File "/home/luki/UFADE/ufade.py", line 125, in bu_menu
    perf_logical_plus(None)
  File "/home/luki/UFADE/ufade.py", line 512, in perf_logical_plus
    Backup.from_path(backup_path=udid, password="12345").unback(".tar_tmp/itunes_bu")
  File "/home/luki/Downloads/pyiosbackup-master/pyiosbackup/backup.py", line 109, in unback
    for file in self.iter_files():
  File "/home/luki/Downloads/pyiosbackup-master/pyiosbackup/backup.py", line 183, in iter_entries
    for metadata in self._manifest_db.get_all_entries():
  File "/home/luki/Downloads/pyiosbackup-master/pyiosbackup/manifest_dbs/sqlite3.py", line 87, in _load_entry
    mb_info = archiver.unarchive(entry['file'])  # type: MBFile
  File "/home/luki/.local/lib/python3.10/site-packages/bpylist2/archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
  File "/home/luki/.local/lib/python3.10/site-packages/bpylist2/archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
  File "/home/luki/.local/lib/python3.10/site-packages/bpylist2/archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "/home/luki/Downloads/pyiosbackup-master/pyiosbackup/manifest_dbs/sqlite3.py", line 41, in decode_archive
    encryption_key=archive_obj.decode('EncryptionKey').NSdata if 'EncryptionKey' in archive_obj.object else b'',
AttributeError: 'bytes' object has no attribute 'NSdata'
                                                              luki@luki-Katana-GF76-11UD:~/UFADE$

**Comment by prosch88** [comment]
ok. Pull and check again.

**Comment by ogi82** [comment]
Hi ! now it works great, congratulations on a job well done and thank you very much. I have a question: do you know any open source program for parsing iOS backups? Something like Ufed Analyzer. Will iTunes backup be decrypted in the program?

**Comment by prosch88** [comment]
@ogi82 With the Logical+ flow (not the UFED one) UFADE tries do decrypt the Backup. This was raising your error. You can parse this Backup with iLeapp or have a look at IPED (https://github.com/sepinf-inc/IPED)

**Comment by prosch88** [comment]
@stark4n6 I did an update. Please pull and try again.

**Comment by stark4n6** [comment]
@prosch88 I haven't forgotten about this, life's been a bit hectic. I will try testing on the newest code hopefully this weekend and will let you know what happens

**Comment by stark4n6** [comment]
@prosch88 I believe my issues are good now as of the newest code/release, going to close this for now but will let you know if I run into any issues in the future, thanks for an awesome tool!
