### ISSUE TITLE
Allow changing the default Backup password

### ISSUE THREAD

**Issue by KirkLandTrip** [prosch88/UFADE#3]
Hello,
The default backup password (12345) isn't detected automatically in cellebrite PA but I think 1234 does (at least in my lab)
Can we have an option to change the default password used by UFADE?

Thank you!

**Comment by prosch88** [comment]
Either this or simply setting the default password to 1234.

If you use the"UFED-Style" Advanced logical Backup, PA will read the backup from the UFD file.

**Comment by stark4n6** [comment]
Take a look here, defaults for different tools are all over the place [https://blog.elcomsoft.com/2022/11/ios-backups-leftover-passwords/](https://blog.elcomsoft.com/2022/11/ios-backups-leftover-passwords/)

I guess it really depends on what tools you're using to read them.

**Comment by stark4n6** [comment]
@prosch88 I agree with this method, just wanted to throw it out there. I would think most tools should prompt for the backup password if it's not the default they are looking for (if the tool is smart enough 😄)
