### ISSUE TITLE
UFED-style Logical+ UFD format compatibility: should prepend "FileDump=" for filename under [Dumps]

### ISSUE THREAD

**Issue by jensstigaard** [prosch88/UFADE#7]
During load of a UFED-style Logical+ acquisition of a iPhone 15 in Cellebrite Physical Analyzer version 7.69, it loads but without any artifacts.

The actual error related to why the data is not loading, shows by opening the trace window.
An error shows "Extraction dump not found".
By revisiting the .UFD file, related to the acquisition, and comparing to another .UFD (from another acquistion, another iDevice, performed by another UFD-compatible acquisition method, and known compatible with PA 7.69), it shows that the syntax is slightly different.

In the UFADE-created .UFD file, the `[Dumps]` section basically contains one line, stating the filename of the .zip file containing the acquired data.
By prepending `FileDump=` to the line containing the filename, it is made identical in syntax with the other .UFD file, and then it works when loading into PA.

**Comment by prosch88** [comment]
Yes, this was taken out by mistake with a recent change.
