### ISSUE TITLE
After successful acquisition: Show some buttons to the user, e.g. "Return to home" and "Unpair"

### ISSUE THREAD

**Issue by jensstigaard** [prosch88/UFADE#8]
When a acquisition is completed, I find it natural and desired to display some options for the user, e.g. return to the home screen.
This is not currently implemented.
The current flow is that the device info is shown in the left pane, but besides this, there is no options available for the user. The application should basically be shut down and opened again.
It could be changed and implemented by showing some buttons, e.g. "Home" and (perhaps also) "Unpair device".
I hope it makes sense.

**Comment by prosch88** [comment]
Currently, if the flow is working you should get an "OK" button and go back to the acquisition Menü. You should be able to navigate the GUI from there.

The left pane is for Information only. If no navigation is possible in the right pane, something went wrong.
