### ISSUE TITLE
Request for collab project

### ISSUE THREAD

**Issue by DRCRecoveryData** [prosch88/UFADE#9]
Hi,

I have made a gui using pyqt6 before for an agency in Viet Nam and I wanna get further development can you check my project to merge UFADE to that gui?

https://github.com/DRCRecoveryData/IOS-Backup-Tool

**Comment by prosch88** [comment]
I'm not sure what you are, trying to achieve. If you want the functionality of UFADE, you can simply use it. You may fork it and change whatever you need for your workflow.

Right now your tool is performing an backup. You should implement a flow to activate the backup encryption.

Also you are using subprocesses for pmd3. You can use it's functions directly via the API. Look at the cli commands in the pmd3 repo to learn how to do so.
